prostorová-data/draft/index.html
oprava chyb a překlepů, učesání textu, oprava rozsypaného formátování od Kuby
=> uprava textu o publikaci prostorovych dat a oprava chyb a preklepu

prostorová-data/draft/index.html
Přidal jsem reference skrz specref.
=> Issue #22 - specrefs

prostorová-data/draft/index.html
Přidal jsem reference skrz specref.
=> opravena chyba

prostorová-data/draft/index.html
Přidal jsem reference skrz specref.
=> opravena chyba 2

prostorová-data/draft/index.html
=> Edited formating

prostorová-data/draft/index.html
=> Přidány linky

prostorová-data/draft/index.html
=> fixed #27 and #28

prostorová-data/draft/index.html
=> examples for services + restructuralization

prostorová-data/draft/index.html
=> edited links

prostorová-data/draft/index.html
použotého -> použitého
+ auto-odmazání nepotřebných mezer
=> preklep fix

parlamentní-data/draft/index.html
=> fixing #70, #71, #72

prostorová-data/draft/index.html
zapracováno do OFN. doporučeno použití formátu GML nebo GeoPackage, případně atribut crs
=> vyřešení issue #86

prostorová-data/draft/index.html
=> vyřešen github issue #88

adresy/draft/index.html, faktury/draft/index.html, prostorová-data/draft/index.html
změny v index.html
je třeba dodělat ještě příklady a schémata podle toho
první je třeba schválit, jestli má cenu to dělat
=> #136 Update OFN adresy

témata-dizertačních-prací/draft/index.html
Doplněny popisy a příklady u další trojice položek.
=> Doplnění popisu a příkladů u položek Klíčová slova, Kontext práce, Doporučovaná pracoviště

adresy/draft/index.html, adresy/draft/schémata/adresa.json, adresy/draft/schémata/adresa.xsd
momc -> název momc
městský obvod -> městský obvod/městaká část
překlep v </br> opraven
=> opravy chyb

adresy/draft/index.html
=> trapná chyba

adresy/draft/css/ssp.css, adresy/draft/index.html
upřesňující mapování atributů na ontologii
=> přidána položka význam ke každému atributu

adresy/draft/index.html
po kontrole jsem našel ještě dvě použití zkrácených názvů nově změněných termů ze slovníku OFN-A
=> minor změny

adresy/draft/index.html
=> uppercase -> lowercase
